### ISSUE TITLE
SDK 4.0.0 Compile errors for WebGL build

### ISSUE THREAD

**Issue by Dazlonar** [Leanplum/Leanplum-Unity-SDK#124]
## Expected Behavior
WebGL builds without any problems.

## Actual Behavior
Compilation errors when running WebGL build.
`Error	CS0103	The name 'leanplumSocket' does not exist in the current context`

## Steps to Reproduce the Problem

  1. Download & install Leanplum Unity SDK 4.0.0
  1. Switch platform to WebGL
  1. Compile project

## Specifications

  - Version: 4.0.0
  - Platform: WebGL

**Comment by nzagorchev** [comment]
Compile time preprocessors can be put in place to resolve this:
```
#if !UNITY_WEBGL
        internal static LeanplumSocket leanplumSocket;
#endif
```

We will fix it in the SDK and have an internal item for this already.
