### ISSUE TITLE
Barebones project, breaks when exported to iOS

### ISSUE THREAD

**Issue by benmarten** [Leanplum/Leanplum-Unity-SDK#13]
So I ran into this issue, earlier when testing on latest Unity and exporting as iOS/xcode project.
Anyone has quick thoughts on how to fix it? It seems to have todo with Metal Framework, maybe related to new Unity IDE version...

![screen shot 2017-10-11 at 1 28 48 pm](https://user-images.githubusercontent.com/5960238/31475635-c5f3fd68-aeb6-11e7-877a-b5277c870e3b.jpg)

**Comment by benmarten** [comment]
@alexisoyama was this the similar issue you were getting?

**Comment by alexisoyama** [comment]
One of the way to get away from this issue is by using XCode 8. Haven't found out a solution yet. It's likely a Unity bug.

**Comment by alexisoyama** [comment]
Closing this since this is more of Unity's issue. Re-open if there is something we can do from our end.
