### ISSUE TITLE
Suggestion: Use Use Unity Jar Resolver for Android dependencies

### ISSUE THREAD

**Issue by Nezz** [Leanplum/Leanplum-Unity-SDK#17]
The Leanplum SDK depends on several Android libraries that are frequently used by other libraries, which generally leads to version conflicts. A number of SDKs started using the [Unity Jar Resolver](https://github.com/googlesamples/unity-jar-resolver) to fix this issue (for example Facebook SDK). It would be nice if Leanplum would start using this too.

**Comment by AlmirKadric** [comment]
I implemented this and pushed up a PR here: #37

**Comment by milos1290** [comment]
Implemented in 1.7.0. Closing issue
