### ISSUE TITLE
link.webgl.xml and link.xml Build Failure iOS

### ISSUE THREAD

**Issue by derek-williams** [Leanplum/Leanplum-Unity-SDK#21]
These files cause the ILL2CPP to fail when building from the Unity Editor on the iOS platform in Unity 2017.3.0f3. If you remove them the build will succeed.

**Comment by benmarten** [comment]
Which files are you referring to?

**Comment by derek-williams** [comment]
link.webgl.xml and link.xml

**Comment by benmarten** [comment]
Hm, I'm not able to reproduce that... 

I tried building via: `./build.sh --apple-sdk-version=2.0.5 --android-sdk-version=4.0.0`
And used latest Unity: https://github.com/caskroom/homebrew-cask/blob/master/Casks/unity.rb#L2

Can you please test latest Unity version or how do you reproduce this?

**Comment by benmarten** [comment]
I just checked, we have `Scripting backend` set to `IL2CPP` under player settings.

**Comment by benmarten** [comment]
Please reopen if issue persists...
