### ISSUE TITLE
in-app messaging does not work on iOS

### ISSUE THREAD

**Issue by AlmirKadric** [Leanplum/Leanplum-Unity-SDK#38]
## Expected Behavior
iOS displays popup-center window when sending preview message from dashboard

## Actual Behavior
iOS native SDK client not recognized when sending preview message from dashboard
dashboard error is "No test devices are connected."
Android works without issues

## Steps to Reproduce the Problem
  1. create iOS build using with native iOS SDK
  2. send preview message from messages dashboard
  3. no clients connected error message
  4. repeat using android, popup display properly

## Specifications
  - Version: 1.6.5
  - Platform: Unity + iOS
  - Subsystem: in-app messaging

**Comment by AlmirKadric** [comment]
Tested latest master (non-released) version as well, still an issue

**Comment by milos1290** [comment]
I'm not able to reproduce this issue on latest master branch. Is this tested on simulator or device ?

**Comment by AlmirKadric** [comment]
Hi @milos1290, this was tested on actual device, iPad mini to be exact

Are there additional settings required for iOS in comparison to android?
All we did was put the SDK in, setup the SDK and called the start function (appid key etc)
And then sent messages from the dashboard
This seems to work fine for Android

**Comment by milos1290** [comment]
Make sure you are exporting development build, also make sure that you set development app id and key. The preview will only work in debug builds not the release ones.

**Comment by milos1290** [comment]
Its checking XCode release settings, you have to check `Development build` in unity export dialog along with `Run in XCode as Debug`

**Comment by AlmirKadric** [comment]
Well that's not very user friendly

Right now there are 2 different ways to define a development build and honestly we should only care about the development key, especially since this is the behaviour already on Android and that being the behaviour in other KPI service's SDKs.

Can you remove the need for the XCode Debug Build option? It really doesn't serve a purpose as far as I can tell, and I should be able to create a Release build using debug keys to test a Release build in a development environment.
