### ISSUE TITLE
use of @import when C++ modules are disabled

### ISSUE THREAD

**Issue by AlmirKadric** [Leanplum/Leanplum-Unity-SDK#39]
## Expected Behavior
Unity project builds iOS target without issues

## Actual Behavior
`use of @import when C++ modules are disabled` error during build
setting of `Build Settings->Enable the modules (C and Objective-C)->True` does not resolve the issue as the header file is being imported by `.mm` files which are import as Objective-C files and not Objective-C++ files by XCode.

## Steps to Reproduce the Problem
  1. Import 1.6.5 Unity SDK
  2. Build iOS target in Unity
  3. Start build in XCode
  4. Error occurs

## Specifications
  - Version: 1.6.5
  - Platform: Unity +iOS
  - Subsystem: N/A
 - XCode Version: 10.1

**Comment by AlmirKadric** [comment]
this seems to be fixed in the latest non-release master version of the unity SDK, we can resolve the issue once the latest release has the correct framework included

**Comment by CraigLacey** [comment]
Is there a time frame on this fix? Running into this issue on Unity Cloud Builds at the moment and it would be nice to know when this is expected to be working. 
Thanks.

**Comment by milos1290** [comment]
I'll double check again and i'll release new version if everything looks good.

**Comment by CraigLacey** [comment]
@milos1290 How's that update looking?

**Comment by milos1290** [comment]
Fix was merged on iOS side, waiting for Android release before publishing new unity version, sorry for delay.

**Comment by CraigLacey** [comment]
@milos1290 Was this fix included in the latest unity package? I see there was an update a few days ago.

**Comment by milos1290** [comment]
not yet sorry, still waiting for iOS release before publishing new version of unity SDK.

**Comment by milos1290** [comment]
Closing issue, fixed in 1.7.0
