### ISSUE TITLE
Unity 2017.1 AssetBundle exception

### ISSUE THREAD

**Issue by Nezz** [Leanplum/Leanplum-Unity-SDK#9]
With Unity 2017.1 we get the following exception whenever Leanplum runs a request:
```
Failed to decompress data for the AssetBundle 'Memory'.
UnityEngine.WWW:get_assetBundle()
LeanplumSDK.<RunRequest>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```
It seems to me that the issue is here:
https://github.com/Leanplum/Leanplum-Unity-SDK/blob/master/LeanplumSample/Assets/WebPlayerTemplates/DoNotCompile/Leanplum/LeanplumUnityHelper.cs#L161-L162
```C#
String.IsNullOrEmpty(www.error) && !isAsset ? www.text : null,
String.IsNullOrEmpty(www.error) ? www.assetBundle : null));
```
should be
```C#
String.IsNullOrEmpty(www.error) && !isAsset ? www.text : null,
String.IsNullOrEmpty(www.error) && isAsset ? www.assetBundle : null));
```

**Comment by alexisoyama** [comment]
Thanks for identifying the issue! When you have time can you make a PR to the develop branch?

**Comment by alexisoyama** [comment]
Above PR fixes this issue. Will keep the issue opened until we make a public release.

**Comment by trdinich** [comment]
I'm running into this issue as well after upgrading Unity to 2017.1.  Could you advise me on what the best course of action is?  i.e. let me know when this will be fixed in a public SDK or could you shoot me over a dev SDK that I could import to fix this issue in the meantime?

**Comment by asaia** [comment]
After upgrading to 2017.1.0f3 I'm also getting the above error running Leanplum Unity SDK 1.4.2

Failed to decompress data for the AssetBundle 'Memory'.
UnityEngine.WWW:get_assetBundle()
LeanplumSDK.<RunRequest>c__Iterator0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I don't have the LeanplumSample folder installed so the above patch does not fix this problem. I see this error when dragging and configuring the LeanPlum prefab into an empty scene and pressing play.

**Comment by Nezz** [comment]
@asaia My fix is to the `LeanplumSDK.dll`. Your issue should be fixed by the next SDK version.
@alexisoyama Can you guys release an update? It's been a month...

**Comment by benmarten** [comment]
Tracking this internally here: https://leanplum.atlassian.net/browse/LP-5763 and https://leanplum.atlassian.net/browse/LP-5764

**Comment by alexisoyama** [comment]
@Nezz We will soon. Sorry for the delay. We thought the next iOS and Android will come out very soon and wanted to package those with it. We got some hiccups along the way and those got delayed. So instead we will probably be releasing Unity with this fix without waiting for them.

**Comment by benmarten** [comment]
Fixed by https://github.com/Leanplum/Leanplum-Unity-SDK/releases/tag/1.4.3
